Add su directive
logrotate complains if the directories where it is rotating logs are not
secure. Example error:

error: skipping "/usr/local/fedora/tomcat/logs/mylogfile.log" because parent
       directory has insecure permissions (It's world writable or writable by
       group which is not "root") Set "su" directive in config file to tell
       logrotate which user/group should be used for rotation.

This small change will make logrotate work.